# Blog
keywords: hais,hais1992,海生,Hello_海生,韦海生
author: Author hais1992,hais1992@163.com
description: 一个屌丝程序员的个人记事本！
avatar: /images/favicon.png

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: hais1992@163.com
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
